export const titles = {
	Next: [
		'Next.js vs. Create React App: Choosing the Right Framework',
		'Styling in Next.js: CSS Modules, Styled Components, and Tailwind CSS',
		'Server-Side Rendering with Next.js: Boosting Performance and SEO',
		'Authentication in Next.js: Implementing User Sign-up and Login',
		'Building Dynamic Websites with Next.js and API Routes',
		'Optimizing SEO in Next.js: Best Practices for Search Engine Visibility',
		'Next.js and GraphQL: Building Efficient Data Fetching Solutions',
		'CSS in Next.js: CSS Modules, Styled Components, and Tailwind CSS',
		'Next.js Deployment Strategies: Vercel, Netlify, and Beyond',
		'Progressive Web Apps (PWAs) with Next.js: Offline Support and Installability',
	],
	TS: [
		'Mastering Generics in TypeScript: A Comprehensive Guide',
		'TypeScript 4.6 Update: Enhancements to Error Messages and Diagnostics',
		'Advanced Techniques: Type Inference and Generics in TypeScript',
		"TypeScript 4.8 Preview: A Deep Dive into Record Types and First-Class 'await'",
		'TypeScript Design Patterns: Leveraging Generics for Reusable Code',
		"TypeScript 4.7's Fresh Features: 'this' Types, Constructor Parameters, and More",
		'Effective Use of Generic Types in TypeScript Projects',
		"TypeScript 4.9's Innovations: GlobalThis, Performance Improvements, and More",
		'TypeScript Generics Demystified: Practical Examples and Best Practices',
		"TypeScript 4.3 Preview: A Deep Dive into Record Types and First-Class 'await'",
	],
	React: [
		"Getting Started with React: A Beginner's Guide",
		'React Hooks Explained: State and Side Effects Made Easy',
		'Advanced React Patterns: Render Props, HOCs, and Function Components',
		'Building a Real-Time Chat App with React and Firebase',
		'React Router v6: Navigating Through Your Single Page Application',
		'Testing React Applications: Jest, Enzyme, and Best Practices',
		'Optimizing Performance in React: Profiling and Code Splitting',
		'Context API vs. Redux: State Management in React',
		'React Native Development: Building Cross-Platform Mobile Apps',
		'Server-Side Rendering (SSR) with React: Next.js and Beyond',
	],
	postgres: [
		'Introduction to PostgreSQL: A Powerful Open-Source Relational Database',
		'PostgreSQL vs. MySQL: Choosing the Right Database for Your Project',
		"Getting Started with psql: PostgreSQL's Command-Line Tool",
		'Schema Design Best Practices in PostgreSQL',
		'Managing Indexes for Performance Optimization in PostgreSQL',
		'Data Migration in PostgreSQL: Tools and Strategies',
		'Advanced SQL Techniques for Querying PostgreSQL Databases',
		'Securing Your PostgreSQL Database: Authentication and Authorization',
		'Scaling PostgreSQL: High Availability and Replication Strategies',
		'PostgreSQL Performance Tuning: Tips for Faster Queries and Throughput',
	],
	prisma: [
		'Getting Started with Prisma: Modern Database Access for Node.js and TypeScript',
		'Prisma vs. Sequelize: Choosing an ORM for Your Node.js Project',
		'Creating a RESTful API with Prisma and Express.js',
		'Real-time Data with Prisma and GraphQL Subscriptions',
		'Modeling Data with Prisma: Schema Design Best Practices',
		'Migrating from Sequelize to Prisma: A Step-by-Step Guide',
		'Advanced Querying with Prisma: Filters, Pagination, and Sorting',
		'Authentication and Authorization with Prisma and Passport.js',
		'Deploying Prisma: Hosting Your Database and API in the Cloud',
		'Prisma and Serverless Functions: Building Scalable Backend Services',
	],
	nextAuth: [
		'NextAuth.js: Simplifying Authentication in Next.js Applications',
		'Implementing OAuth2 Authentication with NextAuth.js',
		'NextAuth.js vs. Passport.js: Choosing the Right Authentication Solution',
		'Customizing User Authentication Flows with NextAuth.js',
		'Adding Social Authentication (Google, Facebook, Twitter) to Your Next.js App with NextAuth.js',
		'Securing Your Next.js API Routes with NextAuth.js',
		'Multi-factor Authentication (MFA) with NextAuth.js: An Implementation Guide',
		'NextAuth.js and JWT: Managing User Sessions and Tokens',
		'NextAuth.js and User Roles: Implementing Access Control in Your App',
		'Troubleshooting Common Issues with NextAuth.js',
	],
	RQ: [
		'Getting Started with React Query: Data Fetching Made Easy',
		'Optimizing React Applications with React Query',
		'React Query vs. Redux: State Management in Modern React Apps',
		'Server-Side Rendering (SSR) with React Query and Next.js',
		'Caching and Invalidation Strategies in React Query',
		'Pagination and Infinite Scrolling with React Query',
		'Real-time Data with WebSockets and React Query',
		'Authentication and Authorization with React Query',
		'Error Handling and Retry Logic in React Query',
		'Testing React Query Hooks and Queries: Best Practices',
	],
	Tailwind: [
		'Getting Started with Tailwind CSS: A Comprehensive Guide',
		'Tailwind CSS vs. Bootstrap: Choosing the Right CSS Framework',
		'Mastering Layouts with Flexbox and Grid in Tailwind CSS',
		'Customizing and Theming Tailwind CSS for Your Project',
		'Responsive Web Design with Tailwind CSS: Mobile-First Approach',
		'Optimizing Performance in Tailwind CSS: PurgeCSS and Beyond',
		'Building Beautiful UI Components with Tailwind CSS',
		'Working with Forms and Input Validation in Tailwind CSS',
		'Animations and Transitions in Tailwind CSS: Adding Interactivity to Your UI',
		'Tailwind CSS Best Practices: Tips and Tricks for Efficient Development',
	],
	shadcn: [
		'Shadcn: Building Responsive Websites with Ease',
		'Material-UI: Implementing Material Design in React Apps',
		'Semantic UI: Streamlining UI Development with CSS Frameworks',
		'Ant Design: Designing Modern Web Applications with React',
		'Foundation: A Solid Base for Responsive Web Development',
		'Bulma: Quick and Customizable CSS Framework for Web Design',
		'Tailwind CSS: Utility-First CSS Framework for Rapid UI Development',
		'Chakra UI: Building Accessible and Customizable React Components',
		'Vuetify: Material Design for Vue.js Applications',
		'Element UI: Creating Rich Web Apps with Vue.js Components',
	],
};
